### ISSUE TITLE
ImportError: No module named _caffe

### ISSUE THREAD

**Issue by zkl99999** [mjq11302010044/RRPN#40]
root@63b86f5db157:/workspace/gitzkl/RRPN# python ./tools/rotation_demo.py
Traceback (most recent call last):
  File "./tools/rotation_demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "/workspace/gitzkl/RRPN/tools/../lib/fast_rcnn/test.py", line 16, in <module>
    import caffe
  File "/workspace/gitzkl/RRPN/tools/../caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/workspace/gitzkl/RRPN/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named _caffe

但是
但是在该容器下 跑 python
import caffe
正常运行，没有报错，

又重新
/opt/caffe/build/tools/caffe
cd /opt/caffe/build
make pycaffe
编译ok
[100%] Built target pycaffe

但还是
python ./tools/rotation_demo.py，出现上述错误，

环境是docker 建立的 nvidia-docker run -ti bvlc/caffe:gpu caffe --version

**Comment by famunir** [comment]
make sure you have done the following:
_make -j4 && make pycaffe_
